version: '3'

services:
  soundcapture:
    build: .
    volumes:
      - /mnt/hgfs/soundcapture:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    environment:
      - ALSA_DEVICE=hw:1,0
    ports:
      - 3000:3000
      - 9229:9229
      - 10010:10010
    devices:
      - /dev/snd
    command: npm run debug